# Generated by Django 5.0.1 on 2024-12-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterygame',
            name='concurso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lotterygame',
            name='sorteados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lotteryticket',
            name='concurso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
