# Generated by Django 5.0.1 on 2024-12-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0002_lotterygame_concurso_lotterygame_sorteados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryticket',
            name='sorteados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
