# Generated by Django 5.0.1 on 2024-12-09 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_app', '0003_lotteryticket_sorteados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotterygame',
            options={'verbose_name': 'Jogo de Loteria', 'verbose_name_plural': 'Jogos de Loteria'},
        ),
        migrations.AlterModelOptions(
            name='lotteryticket',
            options={'verbose_name': 'Bilhete de Loteria', 'verbose_name_plural': 'Bilhetes de Loteria'},
        ),
        migrations.AlterField(
            model_name='lotterygame',
            name='concurso',
            field=models.IntegerField(default=0, verbose_name='Número do concurso'),
        ),
        migrations.AlterField(
            model_name='lotterygame',
            name='historical_data',
            field=models.FileField(blank=True, null=True, upload_to='historical_data/', verbose_name='Arquivo de dados históricos'),
        ),
        migrations.AlterField(
            model_name='lotterygame',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do jogo'),
        ),
        migrations.AlterField(
            model_name='lotterygame',
            name='numbers_to_choose',
            field=models.IntegerField(verbose_name='Quantidade de números a escolher'),
        ),
        migrations.AlterField(
            model_name='lotterygame',
            name='sorteados',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Números sorteados'),
        ),
        migrations.AlterField(
            model_name='lotterygame',
            name='total_numbers',
            field=models.IntegerField(verbose_name='Total de números disponíveis'),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='concurso',
            field=models.IntegerField(verbose_name='Número do concurso'),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery_app.lotterygame', verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='generation_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automático'), ('ai', 'Inteligência Artificial')], max_length=20, verbose_name='Método de geração'),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='numbers',
            field=models.JSONField(verbose_name='Números escolhidos'),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='sorteados',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Números sorteados'),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
